language: php
php:
  - '7.0'
  - nightly

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi